mkdir A/cpp
touch A/cpp/code.cpp
mkdir B/cpp
touch B/cpp/code.cpp
mkdir C/cpp
touch C/cpp/code.cpp
mkdir D/cpp
touch D/cpp/code.cpp
mkdir E/cpp
touch E/cpp/code.cpp
mkdir F/cpp
touch F/cpp/code.cpp
mkdir G/cpp
touch G/cpp/code.cpp
mkdir H/cpp
touch H/cpp/code.cpp
mkdir I/cpp
touch I/cpp/code.cpp
mkdir J/cpp
touch J/cpp/code.cpp
mkdir K/cpp
touch K/cpp/code.cpp
mkdir L/cpp
touch L/cpp/code.cpp
mkdir M/cpp
touch M/cpp/code.cpp
mkdir N/cpp
touch N/cpp/code.cpp
mkdir O/cpp
touch O/cpp/code.cpp
mkdir P/cpp
touch P/cpp/code.cpp
mkdir Q/cpp
touch Q/cpp/code.cpp
mkdir R/cpp
touch R/cpp/code.cpp
mkdir S/cpp
touch S/cpp/code.cpp
mkdir T/cpp
touch T/cpp/code.cpp