mkdir A/python
touch A/python/code.py
mkdir B/python
touch B/python/code.py
mkdir C/python
touch C/python/code.py
mkdir D/python
touch D/python/code.py
mkdir E/python
touch E/python/code.py
mkdir F/python
touch F/python/code.py
mkdir G/python
touch G/python/code.py
mkdir H/python
touch H/python/code.py
mkdir I/python
touch I/python/code.py
mkdir J/python
touch J/python/code.py
mkdir K/python
touch K/python/code.py
mkdir L/python
touch L/python/code.py
mkdir M/python
touch M/python/code.py
mkdir N/python
touch N/python/code.py
mkdir O/python
touch O/python/code.py
mkdir P/python
touch P/python/code.py
mkdir Q/python
touch Q/python/code.py
mkdir R/python
touch R/python/code.py
mkdir S/python
touch S/python/code.py
mkdir T/python
touch T/python/code.py

mkdir A/js
touch A/js/code.js
mkdir B/js
touch B/js/code.js
mkdir C/js
touch C/js/code.js
mkdir D/js
touch D/js/code.js
mkdir E/js
touch E/js/code.js
mkdir F/js
touch F/js/code.js
mkdir G/js
touch G/js/code.js
mkdir H/js
touch H/js/code.js
mkdir I/js
touch I/js/code.js
mkdir J/js
touch J/js/code.js
mkdir K/js
touch K/js/code.js
mkdir L/js
touch L/js/code.js
mkdir M/js
touch M/js/code.js
mkdir N/js
touch N/js/code.js
mkdir O/js
touch O/js/code.js
mkdir P/js
touch P/js/code.js
mkdir Q/js
touch Q/js/code.js
mkdir R/js
touch R/js/code.js
mkdir S/js
touch S/js/code.js
mkdir T/js
touch T/js/code.js